services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: khmenu-load-balancer
    depends_on:
      - express
    environment:
      - NGINX_SERVER_NAME=localhost
      - EXPRESS_HOST_1=${EXPRESS_CONTAINER}-1
      #- EXPRESS_HOST_2=${EXPRESS_CONTAINER}-2
      #- EXPRESS_HOST_3=${EXPRESS_CONTAINER}-3
      - EXPRESS_PORT=4000
      - NGINX_MAX_BODY=100M
    ports:
      - 4000:4000
  express:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./index.js:/app/index.js
      - .env:/app/.env
      - ./uploads:/app/uploads
    #scale: 3
    depends_on:
      - mongodb
      - redis
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: khmenu-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:5
    container_name: khmenu-redis
    ports:
      - 6379:6379
volumes:
  mongodbdata:
